language: csharp
mono: latest
dotnet: 3.1.200
before_install:
  - cd src
script:
  - dotnet restore
  - msbuild
  #- dotnet test ../tests/bin/Debug/netcoreapp3.1/tests.dll
  - dotnet test ./Org.OpenAPITools.Test/bin/Debug/net47/Org.OpenAPITools.Test.dll
